/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.ui;

import hotel.database.DatabaseConnection;
import java.awt.Image;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;


public class CheckOut extends javax.swing.JFrame {

    /**
     * Creates new form CheckOut
     */
    //*******************************************************************//
     //*******************************************************************//
     //          This Method sets the window display properties.          //
     //*******************************************************************//
     //*******************************************************************//
    private void customizeFrameAppearance() {
        //Change the frame
        this.getContentPane().setBackground(new java.awt.Color(240, 240, 240)); 
        //Change frame size
        this.setSize(400, 300);
        // Change frame address
        this.setTitle("Hotel Management - Check Out");
        //  Change the Frame Icon
        ImageIcon appIcon = new ImageIcon("src/images/check-out.png");   
        this.setIconImage(appIcon.getImage());

  }
    public CheckOut() {
        customizeFrameAppearance();
        initComponents();
        UIHelper.setLabelProperties(CheckOutPageLabel, "Check Out", UIHelper.ImagePaths.CHECK_OUT_ICON);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CheckOutButton = new javax.swing.JButton();
        CheckOutPageLabel = new javax.swing.JLabel();
        RoomNoLabel = new javax.swing.JLabel();
        EnterRoomNoTextField = new javax.swing.JTextField();
        BackToHomePageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 150));

        CheckOutButton.setText("Check Out");
        CheckOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutButtonActionPerformed(evt);
            }
        });

        CheckOutPageLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CheckOutPageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CheckOutPageLabel.setText("Check Out");

        RoomNoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RoomNoLabel.setText("Enter Room Number");

        EnterRoomNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterRoomNoTextFieldActionPerformed(evt);
            }
        });

        BackToHomePageButton.setText("Back");
        BackToHomePageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToHomePageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(BackToHomePageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CheckOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RoomNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(CheckOutPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(172, 172, 172))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(EnterRoomNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(159, 159, 159)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(CheckOutPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(RoomNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EnterRoomNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackToHomePageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterRoomNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterRoomNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnterRoomNoTextFieldActionPerformed

    private void CheckOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutButtonActionPerformed
    // Get the Room number in Text field
    int roomNumber = Integer.parseInt(EnterRoomNoTextField.getText()); 

    // Creat a query to determine room statuses and dates
    String query = "UPDATE RoomsInformation r "
            + "LEFT JOIN RoomsInformation b ON r.RoomNumber = b.RoomNumber "
            + "SET r.RoomStates = 'Available', b.CheckInDate = NULL, b.CheckOutDate = NULL "
            + "WHERE r.RoomNumber = ? AND b.CheckInDate IS NOT NULL AND b.CheckOutDate IS NOT NULL";

    try {
        // Start connection with database
        Connection conn = DatabaseConnection.getInstance().getConnection();
        PreparedStatement stmt = conn.prepareStatement(query);
        // Set value in the query
        stmt.setInt(1, roomNumber);
        // Execute the query
        int rowsAffected = stmt.executeUpdate();
        if (rowsAffected > 0) {
        // loading incon
        ImageIcon originalIcon = new ImageIcon("src/images/success.png"); 
        Image iconImage = originalIcon.getImage(); 
        // Resized image width and hieght
        Image resizedImage = iconImage.getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH);

        // call function resized Icon
        ImageIcon resizedIcon = new ImageIcon(resizedImage);
        JOptionPane.showMessageDialog(this, "Check-out successful. The room is now available.", "Success", JOptionPane.INFORMATION_MESSAGE, resizedIcon);

        } else {
            // loading incon
            ImageIcon originalIcon = new ImageIcon("src/images/unsuccess.png"); 
            Image iconImage = originalIcon.getImage(); 
            // Resized image width and hieght
            Image resizedImage = iconImage.getScaledInstance(40, 40, java.awt.Image.SCALE_SMOOTH);
            // call function resized Icon
            ImageIcon resizedIcon = new ImageIcon(resizedImage); 
            JOptionPane.showMessageDialog(this, "No reservation found for this room number or the room is not reserved.", "Failure", JOptionPane.ERROR_MESSAGE,resizedIcon);
        }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "An error occurred during check-out.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CheckOut.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_CheckOutButtonActionPerformed

    private void BackToHomePageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToHomePageButtonActionPerformed
         // Close Check In page
        this.dispose();
        // Opening Home apge
        Home homePage = new Home();  
        homePage.reloadImages();
        homePage.setVisible(true);
    }//GEN-LAST:event_BackToHomePageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToHomePageButton;
    private javax.swing.JButton CheckOutButton;
    private javax.swing.JLabel CheckOutPageLabel;
    private javax.swing.JTextField EnterRoomNoTextField;
    private javax.swing.JLabel RoomNoLabel;
    // End of variables declaration//GEN-END:variables
}
