/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.ui;

import hotel.database.DatabaseConnection;
import hotel.guest.Guest;
import hotel.guest.Guests;
import hotel.room.Room;
import hotel.room.RoomFactory;
import hotel.room.Rooms;
import hotel.ui.UIHelper.ImagePaths;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class NewRoom extends javax.swing.JFrame {

    //private String roomNumber;
    

    /**
     * Creates new form CheckIn
     */
     //*******************************************************************//
     //*******************************************************************//
     //          This Method sets the window display properties.          //
     //*******************************************************************//
     //*******************************************************************//
    private void customizeFrameAppearance() {
        //Change the frame
        this.getContentPane().setBackground(new java.awt.Color(240, 240, 240)); 
        //Change frame size
        this.setSize(400, 300);
        // Change frame address
        this.setTitle("Hotel Management - New Guest");
        //  Change the Frame Icon
        ImageIcon appIcon = new ImageIcon("src/images/check-in.png");  
        this.setIconImage(appIcon.getImage());

  }
    public NewRoom() {
        customizeFrameAppearance();
        initComponents();
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roomTypebuttonGroup = new javax.swing.ButtonGroup();
        Pearsonal_Data_Panel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        roomIdField = new javax.swing.JTextField();
        AddressLabel = new javax.swing.JLabel();
        CityLabel = new javax.swing.JLabel();
        locationField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        standardRoomRadioButton = new javax.swing.JRadioButton();
        deluxeRoomRadioButton = new javax.swing.JRadioButton();
        suiteRoomRadioButton = new javax.swing.JRadioButton();
        availabilityCheckbox = new javax.swing.JCheckBox();
        CheckInPageLabel = new javax.swing.JLabel();
        SearchRoomButton = new javax.swing.JButton();
        backToHomeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLabel.setText("No.");

        roomIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomIdFieldActionPerformed(evt);
            }
        });

        AddressLabel.setText("Available");

        CityLabel.setText("Location");

        locationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Type");

        roomTypebuttonGroup.add(standardRoomRadioButton);
        standardRoomRadioButton.setText("Standard");
        standardRoomRadioButton.setActionCommand("standard");
        standardRoomRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardRoomRadioButtonActionPerformed(evt);
            }
        });

        roomTypebuttonGroup.add(deluxeRoomRadioButton);
        deluxeRoomRadioButton.setText("Deluxe");
        deluxeRoomRadioButton.setActionCommand("deluxe");
        deluxeRoomRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deluxeRoomRadioButtonActionPerformed(evt);
            }
        });

        roomTypebuttonGroup.add(suiteRoomRadioButton);
        suiteRoomRadioButton.setText("Suite");
        suiteRoomRadioButton.setActionCommand("suite");
        suiteRoomRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suiteRoomRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pearsonal_Data_PanelLayout = new javax.swing.GroupLayout(Pearsonal_Data_Panel);
        Pearsonal_Data_Panel.setLayout(Pearsonal_Data_PanelLayout);
        Pearsonal_Data_PanelLayout.setHorizontalGroup(
            Pearsonal_Data_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pearsonal_Data_PanelLayout.createSequentialGroup()
                .addGroup(Pearsonal_Data_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pearsonal_Data_PanelLayout.createSequentialGroup()
                        .addGroup(Pearsonal_Data_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(CityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pearsonal_Data_PanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Pearsonal_Data_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomIdField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(availabilityCheckbox, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(Pearsonal_Data_PanelLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(standardRoomRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deluxeRoomRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suiteRoomRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Pearsonal_Data_PanelLayout.setVerticalGroup(
            Pearsonal_Data_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pearsonal_Data_PanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(Pearsonal_Data_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(roomIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(Pearsonal_Data_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(standardRoomRadioButton)
                    .addComponent(deluxeRoomRadioButton)
                    .addComponent(suiteRoomRadioButton))
                .addGap(18, 18, 18)
                .addGroup(Pearsonal_Data_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(availabilityCheckbox)
                    .addComponent(AddressLabel))
                .addGap(16, 16, 16)
                .addGroup(Pearsonal_Data_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityLabel)
                    .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        CheckInPageLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CheckInPageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CheckInPageLabel.setText("New Room");

        SearchRoomButton.setText("Save");
        SearchRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchRoomButtonActionPerformed(evt);
            }
        });

        backToHomeButton.setText("Back");
        backToHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToHomeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Pearsonal_Data_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(CheckInPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backToHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(SearchRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(CheckInPageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pearsonal_Data_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backToHomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomIdFieldActionPerformed

    private void locationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationFieldActionPerformed

    private void SearchRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchRoomButtonActionPerformed
        // Get Value From Buttons
        //Storing Room data from input Fields without searching for it in the database
        int id = Integer.parseInt(roomIdField.getText()); 
        String type = roomTypebuttonGroup.getSelection().getActionCommand();
        boolean availability = availabilityCheckbox.isSelected();
        String location = locationField.getText();
        
        Room room = RoomFactory.createRoom(id, type, availability, location);
        
        room.save();
        
        Rooms rooms = Rooms.getInstance();
        rooms.addRoom(room);
        
        this.dispose();
        RoomsList roomsList = new RoomsList();  
        roomsList.setVisible(true);
    }//GEN-LAST:event_SearchRoomButtonActionPerformed

    private void backToHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToHomeButtonActionPerformed
         // Close Check In page
        this.dispose();
        // Opening Home apge
        GuestsList guestsList = new GuestsList();  
        guestsList.setVisible(true);
    }//GEN-LAST:event_backToHomeButtonActionPerformed

    private void standardRoomRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardRoomRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_standardRoomRadioButtonActionPerformed

    private void deluxeRoomRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deluxeRoomRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deluxeRoomRadioButtonActionPerformed

    private void suiteRoomRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suiteRoomRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suiteRoomRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JLabel CheckInPageLabel;
    private javax.swing.JLabel CityLabel;
    private javax.swing.JPanel Pearsonal_Data_Panel;
    private javax.swing.JButton SearchRoomButton;
    private javax.swing.JCheckBox availabilityCheckbox;
    private javax.swing.JButton backToHomeButton;
    private javax.swing.JRadioButton deluxeRoomRadioButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JTextField locationField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField roomIdField;
    private javax.swing.ButtonGroup roomTypebuttonGroup;
    private javax.swing.JRadioButton standardRoomRadioButton;
    private javax.swing.JRadioButton suiteRoomRadioButton;
    // End of variables declaration//GEN-END:variables

    private void showRoomDetailsDialogWindowActivated(ActionEvent evt, int roomNumber) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
